name: Compile Bison and Flex

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Bison and Flex
      run: |
        sudo apt-get update
        sudo apt-get install -y bison flex

    - name: Change directory to LexParser
      run: cd LexParser
      working-directory: LexParser

    - name: Compile Bison and Flex files
      run: |
        flex lexer.l
        bison -d parser.y
        gcc lex.yy.c parser.tab.c -o parser

    - name: Run parser with test_file.gst
      run: |
        export YYDEBUG=1
        ./parser < test_file.gst

    - name: Clean up
      run: |
        rm -rf lex.yy.c parser.tab.c parser.tab.h
